### ISSUE TITLE
Can not read blocks (ubuntu)

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/esplora-tapyrus#12]
```
root@490ffc3ab22c:~/src# RUST_BACKTRACE=full cargo run --bin electrs -- -vvvv --timestamp --daemon-dir /tmp/.tapyrus/prod-1905960821 --db-dir /tmp/db --network prod --network-id 1905960821 --electrum-rpc-addr 0.0.0.0:50001 --daemon-rpc-addr tapyrus1:12381 --cookie user:pass
    Finished dev [unoptimized + debuginfo] target(s) in 1.22s
     Running `target/debug/electrs -vvvv --timestamp --daemon-dir /tmp/.tapyrus/prod-1905960821 --db-dir /tmp/db --network prod --network-id 1905960821 --electrum-rpc-addr '0.0.0.0:50001' --daemon-rpc-addr 'tapyrus1:12381' --cookie 'user:pass'`
Config { log: StdErrLog { verbosity: Trace, quiet: false, show_level: true, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Auto }, network: Network { network_type: Prod, id: 1905960821 }, db_path: "/tmp/db/prod", daemon_dir: "/tmp/.tapyrus/prod-1905960821", blocks_dir: "/tmp/.tapyrus/prod-1905960821/blocks", daemon_rpc_addr: V4(172.18.2.1:12381), cookie: Some("user:pass"), electrum_rpc_addr: V4(0.0.0.0:50001), http_addr: V4(127.0.0.1:3000), http_socket_file: None, monitoring_addr: V4(127.0.0.1:4224), jsonrpc_import: false, light_mode: false, address_search: false, index_unspendables: false, cors: None, precache_scripts: None, utxos_limit: 500, electrum_txs_limit: 500, electrum_banner: "Welcome to electrs-esplora 0.4.1", enable_open_assets: false }
2021-02-26T12:10:45.954+00:00 - DEBUG - Server listening on 127.0.0.1:4224
2021-02-26T12:10:45.958+00:00 - DEBUG - Running accept thread
2021-02-26T12:10:45.965+00:00 - INFO - NetworkInfo { version: 40000, subversion: "/Tapyrus Core:0.4.0/", relayfee: 0.00001 }
2021-02-26T12:10:45.966+00:00 - INFO - BlockchainInfo { chain: "1905960821", blocks: 10012, headers: 10012, bestblockhash: "8d265d70be88e0e2a17d23909aca721e6a7fe8e32c8cafe57e4f4074e363b2a3", pruned: false, verificationprogress: 1.0, initialblockdownload: Some(true) }
2021-02-26T12:12:35.888+00:00 - DEBUG - opening DB at "/tmp/db/prod/newindex/txstore"
2021-02-26T12:12:35.929+00:00 - DEBUG - 0 blocks were added
2021-02-26T12:12:35.929+00:00 - DEBUG - opening DB at "/tmp/db/prod/newindex/history"
2021-02-26T12:12:35.941+00:00 - DEBUG - 0 blocks were indexed
2021-02-26T12:12:35.941+00:00 - DEBUG - opening DB at "/tmp/db/prod/newindex/cache"
2021-02-26T12:12:35.958+00:00 - DEBUG - downloading all block headers up to 04ce5d3a7bd4b2ef1a775c3334a0ab88dd8638f605c1b43fb800bde42dbb3167
2021-02-26T12:12:35.963+00:00 - TRACE - downloading 10014 block headers
2021-02-26T12:12:38.680+00:00 - INFO - hash=04ce5d3a7bd4b2ef1a775c3334a0ab88dd8638f605c1b43fb800bde42dbb3167 height=10013 @ 2021-02-26T12:12:32+00:00 (10014 left to index)
2021-02-26T12:12:38.701+00:00 - DEBUG - adding transactions from 10014 blocks using BlkFiles
2021-02-26T12:12:38.702+00:00 - DEBUG - listing block files at "/tmp/.tapyrus/prod-1905960821/blocks/blk*.dat"
thread 'blkfiles_fetcher' panicked at 'failed to index 10014 blocks from blk*.dat files', src/new_index/fetch.rs:140:17
stack backtrace:
   0:     0x559b82aa8924 - backtrace::backtrace::libunwind::trace::hc1c4a1d8ad423b97
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x559b82aa8924 - backtrace::backtrace::trace_unsynchronized::h82274781060cb056
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x559b82aa8924 - std::sys_common::backtrace::_print_fmt::h2a45d89b653a4da8
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x559b82aa8924 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41a0a93ab85e6aa1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x559b82ad325c - core::fmt::write::hdaea18585065a96d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x559b82aa1673 - std::io::Write::write_fmt::h0cea70c809005252
                               at src/libstd/io/mod.rs:1504
   6:     0x559b82aab195 - std::sys_common::backtrace::_print::hd95f9978cc145ca4
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x559b82aab195 - std::sys_common::backtrace::print::hfb25ca2291be47d0
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x559b82aab195 - std::panicking::default_hook::{{closure}}::h44f76cee5dc8591c
                               at src/libstd/panicking.rs:198
   9:     0x559b82aaaed2 - std::panicking::default_hook::h198e1a712910f1e6
                               at src/libstd/panicking.rs:218
  10:     0x559b82aab7f2 - std::panicking::rust_panic_with_hook::hc0b4730bb8013f9d
                               at src/libstd/panicking.rs:511
  11:     0x559b82aab3db - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x559b82aab34b - std::panicking::begin_panic_fmt::h3693eb684a4f728c
                               at src/libstd/panicking.rs:373
  13:     0x559b817bcc5a - esplora_tapyrus::new_index::fetch::blkfiles_fetcher::{{closure}}::h5afec787ce57dfb5
                               at src/new_index/fetch.rs:140
  14:     0x559b819d9d45 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc0e26d883ad7586e
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/sys_common/backtrace.rs:130
  15:     0x559b8194e796 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h9c3bcbeade6494e5
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/mod.rs:475
  16:     0x559b81ae9c24 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he6c6aa591c001123
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:318
  17:     0x559b81af5d57 - std::panicking::try::do_call::ha222c44e4e69fcc2
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
  18:     0x559b81af930d - __rust_try
  19:     0x559b81af0894 - std::panicking::try::h93d5c5dbb018c60c
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
  20:     0x559b81aead06 - std::panic::catch_unwind::hc72f692931484422
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
  21:     0x559b8194cf2d - std::thread::Builder::spawn_unchecked::{{closure}}::h72e52bc93de2ef0b
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/mod.rs:474
  22:     0x559b81850a9f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0aed7e580b40e430
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/ops/function.rs:232
  23:     0x559b82ab090a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1f1fac7de7dd9691
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  24:     0x559b82ab090a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha031f48633a6af54
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  25:     0x559b82ab090a - std::sys::unix::thread::Thread::new::thread_start::h241864caf436e182
                               at src/libstd/sys/unix/thread.rs:87
  26:     0x7f5f5cdfcfa3 - start_thread
  27:     0x7f5f5cd114cf - clone
  28:                0x0 - <unknown>
thread 'main' panicked at 'fetcher thread panicked: Any', src/new_index/fetch.rs:62:9
stack backtrace:
   0:     0x559b82aa8924 - backtrace::backtrace::libunwind::trace::hc1c4a1d8ad423b97
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x559b82aa8924 - backtrace::backtrace::trace_unsynchronized::h82274781060cb056
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x559b82aa8924 - std::sys_common::backtrace::_print_fmt::h2a45d89b653a4da8
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x559b82aa8924 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41a0a93ab85e6aa1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x559b82ad325c - core::fmt::write::hdaea18585065a96d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x559b82aa1673 - std::io::Write::write_fmt::h0cea70c809005252
                               at src/libstd/io/mod.rs:1504
   6:     0x559b82aab195 - std::sys_common::backtrace::_print::hd95f9978cc145ca4
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x559b82aab195 - std::sys_common::backtrace::print::hfb25ca2291be47d0
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x559b82aab195 - std::panicking::default_hook::{{closure}}::h44f76cee5dc8591c
                               at src/libstd/panicking.rs:198
   9:     0x559b82aaaed2 - std::panicking::default_hook::h198e1a712910f1e6
                               at src/libstd/panicking.rs:218
  10:     0x559b82aab7f2 - std::panicking::rust_panic_with_hook::hc0b4730bb8013f9d
                               at src/libstd/panicking.rs:511
  11:     0x559b82aab3db - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x559b82ad1011 - core::panicking::panic_fmt::h1ac71ad045d55416
                               at src/libcore/panicking.rs:111
  13:     0x559b82ad0e33 - core::option::expect_none_failed::hb40004d71d61b685
                               at src/libcore/option.rs:1268
  14:     0x559b8174f3f6 - core::result::Result<T,E>::expect::ha4f216f32a92ca6a
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/result.rs:963
  15:     0x559b817bb537 - esplora_tapyrus::new_index::fetch::Fetcher<T>::map::hc06a0e9704c0a263
                               at src/new_index/fetch.rs:62
  16:     0x559b817a64dc - esplora_tapyrus::new_index::schema::Indexer::update::hc421dc739d46a7c5
                               at src/new_index/schema.rs:247
  17:     0x559b816451c1 - electrs::run_server::h1b4b0fb15e679ee0
                               at src/bin/electrs.rs:61
  18:     0x559b81646a3b - electrs::main::hb5be2ea127031e22
                               at src/bin/electrs.rs:121
  19:     0x559b81642e8b - std::rt::lang_start::{{closure}}::hd420bd76f1d3c7cc
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/rt.rs:67
  20:     0x559b82aabd08 - std::rt::lang_start_internal::{{closure}}::h7a212202ff76034b
                               at src/libstd/rt.rs:52
  21:     0x559b82aabd08 - std::panicking::try::do_call::h6d214a73427d759b
                               at src/libstd/panicking.rs:331
  22:     0x559b82aabd08 - std::panicking::try::hc078f0e11721d1cb
                               at src/libstd/panicking.rs:274
  23:     0x559b82aabd08 - std::panic::catch_unwind::hb31c05be30625612
                               at src/libstd/panic.rs:394
  24:     0x559b82aabd08 - std::rt::lang_start_internal::hcf7fb98a775d5af0
                               at src/libstd/rt.rs:51
  25:     0x559b81642e67 - std::rt::lang_start::hae5396872e757953
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/rt.rs:67
  26:     0x559b81646cda - main
  27:     0x7f5f5cc3c09b - __libc_start_main
  28:     0x559b81642a5a - _start
  29:                0x0 - <unknown>
root@490ffc3ab22c:~/src# 

```

**Comment by Yamaguchi** [comment]
With `--jsonrpc-import` option, no panic occurred and it synchronized successfully

**Comment by Yamaguchi** [comment]
i  have just specified a wrong argument(--daemon-dir /tmp/.tapyrus/prod-1905960821)
